# Generated by Django 4.2.6 on 2023-10-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
